package ru.bmstu.sqlfornosql.analyzer.symbols.variables;

import ru.bmstu.sqlfornosql.analyzer.symbols.SymbolType;

public enum VarTag implements SymbolType {
    SELECT_STMT,
    COL_REF,
    COL_REF_LIST,
    QUALIFIED_NAME,
    ALL_DISTINCT_CLAUSE,
    UNION_INT_OPS,
    ORDER_BY_CLAUSE,
    ORDER_BY_ELEM,
    LIMIT_CLAUSE,
    OFFSET_CLAUSE,
    ASC_DESC,
    TARGET_LIST,
    TARGET_EXPR,
    FROM_LIST,
    WHERE_CLAUSE,
    GROUP_BY_CLAUSE,
    HAVING_CLAUSE,
    TABLE_REF,
    ALIAS_CLAUSE,
    JOIN_TYPE,
    JOIN_QUAL,
    ARITHM_EXPR,
    ARITHM_EXPR_TERM,
    ARITHM_EXPR_FACTOR,
    BOOL_EXPR,
    BOOL_EXPR_TERM,
    BOOL_EXPR_FACTOR,
    DATE_CONST,
    TIME_CONST,
    DATE_TIME_CONST,
    RHS,
    CONST_LIST,
    CONST,
    ARITHM_RHS,
    BOOL_RHS,
    DATE_RHS,
    STRING_RHS
}
